ROKO.Lib.PL.WebUI/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

using ROKO.Lib.BLL.Interface;
using ROKO.Lib.Entities;

namespace ROKO.Lib.PL.WebUI.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAuthorLogic _authorLogic;

        public AuthorController(IAuthorLogic authorLogic)
        {
            _authorLogic = authorLogic;
        }

        // GET: AuthorController
        public ActionResult Index()
        {
            return View();
        }

        // GET: AuthorController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create(Author author)
        {
            try
            {
                //_authorLogic.
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ROKO.Lib.PL.WebUI/Controllers/BookController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

using ROKO.Lib.BLL.Interface;
using ROKO.Lib.Entities;

using System;
using System.Collections.Generic;
using System.Linq;

namespace ROKO.Lib.PL.WebUI.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookLogic _bookLogic;
        private readonly IAuthorLogic _authorLogic;
        private readonly ICatalogLogic _catalogLogic;

        private readonly ILogger<BookController> _logger;

        public BookController(IBookLogic bookLogic,
                              ICatalogLogic catalogLogic,
                              IAuthorLogic authorLogic, ILogger<BookController> logger)
        {
            _bookLogic = bookLogic;
            _authorLogic = authorLogic;
            _catalogLogic = catalogLogic;
            _logger = logger;
        }

        // GET: BookController
        public ActionResult Index()
        {
            IEnumerable<Book> books = _bookLogic.GetAllSpecified();
            return View(books);
        }

        // GET: BookController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BookController/Create
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            ViewBag.authors = _authorLogic.GetAuthors().Select(x => new SelectListItem { Value = x.AuthorID.ToString(), Text = x.FirstName + " " + x.LastName }).ToList();

            _logger.LogInformation($"Message: Admin with login '{User.Identity.Name}' opened Book Creating view. Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(BookController)} Method: {nameof(BookController.Create)}");

            return View("CreateBookWithAuthors");
        }

        // POST: BookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create(Book book, IEnumerable<int> authors)
        {
            try
            {
                var bookId = _bookLogic.Add(book);

                _authorLogic.AddAuthorsToLibraryObject(bookId, authors);

                _logger.LogInformation($"Message: Admin with login '{User.Identity.Name}' added new book with id = {bookId}. Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(BookController)} Method: {nameof(BookController.Create)}");

                return RedirectToAction("Index", "Catalog");
            }
            catch (Exception e)
            {
                _logger.LogError($"ErrorMessage: {e.Message} CurrentUser: {User.Identity.Name} Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(BookController)} Method: {nameof(BookController.Create)}");

                return RedirectToAction("Create");
            }
        }

        // GET: BookController/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BookController/Edit/5
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Book book)
        {
            try
            {
                _bookLogic.Edit(book);

                _logger.LogInformation($"Message: Admin edit book with id = {book.Id}. CurrentUser: {User.Identity.Name} Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(CatalogController)} Method: {nameof(CatalogController.Edit)}");

                return RedirectToAction(nameof(Index), "Catalog");
            }
            catch
            {
                return View();
            }
        }

        // GET: BookController/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BookController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ROKO.Lib.PL.WebUI/Views/Book/CreateBook.cshtml
@model ROKO.Lib.Entities.Book

@{
    ViewData["Title"] = "CreateBook";
}

<h1>Create New Book</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaceOfPublication" class="control-label"></label>
                <input asp-for="PlaceOfPublication" class="form-control" />
                <span asp-validation-for="PlaceOfPublication" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishingHouse" class="control-label"></label>
                <input asp-for="PublishingHouse" class="form-control" />
                <span asp-validation-for="PublishingHouse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublicationOrApplicationYear" class="control-label"></label>
                <input asp-for="PublicationOrApplicationYear" class="form-control" />
                <span asp-validation-for="PublicationOrApplicationYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfPages" class="control-label"></label>
                <input asp-for="NumberOfPages" class="form-control" />
                <span asp-validation-for="NumberOfPages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.AntiForgeryToken()
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Catalog">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ROKO.Lib.PL.WebUI/Views/Book/CreateBookWithAuthors.cshtml
@model ROKO.Lib.PL.WebUI.Models.BookAddingWithAuthors

@{
    ViewData["Title"] = "CreateBookWithAuthors";
}

<h1>CreateBookWithAuthors</h1>

<h4>BookAddingWithAuthors</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Book">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Book.Title" class="control-label"></label>
                <input asp-for="Book.Title" class="form-control" />
                <span asp-validation-for="Book.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.PlaceOfPublication" class="control-label"></label>
                <input asp-for="Book.PlaceOfPublication" class="form-control" />
                <span asp-validation-for="Book.PlaceOfPublication" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.PublishingHouse" class="control-label"></label>
                <input asp-for="Book.PublishingHouse" class="form-control" />
                <span asp-validation-for="Book.PublishingHouse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.PublicationOrApplicationYear" class="control-label"></label>
                <input asp-for="Book.PublicationOrApplicationYear" class="form-control" />
                <span asp-validation-for="Book.PublicationOrApplicationYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.NumberOfPages" class="control-label"></label>
                <input asp-for="Book.NumberOfPages" class="form-control" />
                <span asp-validation-for="Book.NumberOfPages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.ISBN" class="control-label"></label>
                <input asp-for="Book.ISBN" class="form-control" />
                <span asp-validation-for="Book.ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Note" class="control-label"></label>
                <input asp-for="Book.Note" class="form-control" />
                <span asp-validation-for="Book.Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Authors" class="control-label"></label><br>
                <select multiple="multiple" class="js-example-basic-multiple" asp-for="@Model.Authors" asp-items="@(List<SelectListItem>)ViewBag.authors"></select>
                <span asp-validation-for="Authors" class="text-danger"></span>
            </div><br>
            <div>
                @*<button asp-action="Create" asp-controller="Author">Add New Author</button>*@
            </div>
            <div class="form-group">
                @Html.AntiForgeryToken()
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <a asp-action="Index" asp-controller="Catalog">Back to List</a>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <link href="~/css/select2.min.css" rel="stylesheet" />
    <script src="~/js/select2.min.js"></script>
    <script src="~/js/select2connection.js"></script>
}

ROKO.Lib.PL.WebUI/Views/Book/Index.cshtml
@model IEnumerable<ROKO.Lib.Entities.Book>

@{
    ViewData["Title"] = "Index";
}

<h1>All Books</h1>

<p>
    <a asp-action="Create">Create New Book</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Authors)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlaceOfPublication)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishingHouse)
            </th>
            <th>
                <text>PublicationYear</text>
                @*@Html.DisplayNameFor(model => model.PublicationOrApplicationYear)*@
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfPages)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ISBN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Note)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @foreach (var author in item.Authors)
                    {
                        <pre>@author.ToString()</pre>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlaceOfPublication)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublishingHouse)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublicationOrApplicationYear)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfPages)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ISBN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Note)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>