ROKO.Lib.PL.WebUI/Controllers/BookController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

using ROKO.Lib.BLL.Interface;
using ROKO.Lib.Entities;

using System;
using System.Collections.Generic;
using System.Linq;

namespace ROKO.Lib.PL.WebUI.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookLogic _bookLogic;
        private readonly IAuthorLogic _authorLogic;
        private readonly ICatalogLogic _catalogLogic;

        private readonly ILogger<BookController> _logger;

        public BookController(IBookLogic bookLogic,
                              ICatalogLogic catalogLogic,
                              IAuthorLogic authorLogic, ILogger<BookController> logger)
        {
            _bookLogic = bookLogic;
            _authorLogic = authorLogic;
            _catalogLogic = catalogLogic;
            _logger = logger;
        }

        // GET: BookController
        public ActionResult Index()
        {
            IEnumerable<Book> books = _bookLogic.GetAllSpecified();
            return View(books);
        }

        // GET: BookController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BookController/Create
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            ViewBag.authors = _authorLogic.GetAuthors().Select(x => new SelectListItem { Value = x.AuthorID.ToString(), Text = x.FirstName + " " + x.LastName }).ToList();

            _logger.LogInformation($"Message: Admin with login '{User.Identity.Name}' opened Book Creating view. Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(BookController)} Method: {nameof(BookController.Create)}");

            return View("CreateBookWithAuthors");
        }

        // POST: BookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create(Book book, IEnumerable<int> authors)
        {
            try
            {
                var bookId = _bookLogic.Add(book);

                _authorLogic.AddAuthorsToLibraryObject(bookId, authors);

                _logger.LogInformation($"Message: Admin with login '{User.Identity.Name}' added new book with id = {bookId}. Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(BookController)} Method: {nameof(BookController.Create)}");

                return RedirectToAction("Index", "Catalog");
            }
            catch (Exception e)
            {
                _logger.LogError($"ErrorMessage: {e.Message} CurrentUser: {User.Identity.Name} Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(BookController)} Method: {nameof(BookController.Create)}");

                return RedirectToAction("Create");
            }
        }

        // GET: BookController/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BookController/Edit/5
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Book book)
        {
            try
            {
                _bookLogic.Edit(book);

                _logger.LogInformation($"Message: Admin edit book with id = {book.Id}. CurrentUser: {User.Identity.Name} Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(CatalogController)} Method: {nameof(CatalogController.Edit)}");

                return RedirectToAction(nameof(Index), "Catalog");
            }
            catch
            {
                return View();
            }
        }

        // GET: BookController/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BookController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ROKO.Lib.PL.WebUI/Controllers/NewspaperController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using ROKO.Lib.BLL.Interface;
using ROKO.Lib.Entities;
using ROKO.Lib.PL.WebUI.Models;

using System;
using System.Collections.Generic;
using System.Linq;

namespace ROKO.Lib.PL.WebUI.Controllers
{
    public class NewspaperController : Controller
    {
        private readonly ICatalogUnitLogic<Newspaper> _newspaperLogic;
        private readonly ICatalogLogic _catalogLogic;

        private readonly ILogger<NewspaperController> _logger;

        public NewspaperController(ICatalogUnitLogic<Newspaper> newspaperLogic, ICatalogLogic catalogLogic, ILogger<NewspaperController> logger)
        {
            _newspaperLogic = newspaperLogic;
            _catalogLogic = catalogLogic;

            _logger = logger;
        }

        // GET: NewspaperController
        public ActionResult Index()
        {
            IEnumerable<Newspaper> newspapers = _newspaperLogic.GetAllSpecified();
            return View(newspapers);
        }

        // GET: NewspaperController/Details/5
        public ActionResult Details(int id)
        {
            Newspaper newspaper = _newspaperLogic.GetAllSpecified().Where(n => n.Id == id).FirstOrDefault();

            NewspaperViewModel newspaperViewModel = new NewspaperViewModel();
            newspaperViewModel.CurrentNewspaper = newspaper;

            var allNewspapers = _newspaperLogic.GetAllSpecified();

            List<Newspaper> issueList = new List<Newspaper>();

            foreach (var newspaperToChoose in allNewspapers)
            {
                if (newspaper.ISSN != null && newspaper.ISSN == newspaperToChoose.ISSN)
                {
                    issueList.Add(newspaperToChoose);
                }

                if (newspaper.ISSN == null && newspaper.Title == newspaperToChoose.Title && newspaper.PublishingHouse == newspaperToChoose.PublishingHouse)
                {
                    issueList.Add(newspaperToChoose);
                }
            }

            newspaperViewModel.NewspaperIssues = issueList.OrderByDescending(n => n.IssueNumber);

            return View("NewspaperWithIssuesDetails", newspaperViewModel);
        }

        // GET: NewspaperController/Create
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            _logger.LogInformation($"Message: Admin with login '{User.Identity.Name}' opened Newspaper Creating view. Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(NewspaperController)} Method: {nameof(NewspaperController.Create)}");

            return View("CreateNewspaper");
        }

        // POST: NewspaperController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create(Newspaper newspaper)
        {
            try
            {
                var newspaperId = _newspaperLogic.Add(newspaper);

                _logger.LogInformation($"Message: Admin with login '{User.Identity.Name}' added new newspaper with id = {newspaperId}. Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(NewspaperController)} Method: {nameof(NewspaperController.Create)}");

                return RedirectToAction("Index", "Catalog");
            }
            catch (Exception e)
            {
                _logger.LogError($"ErrorMessage: {e.Message} CurrentUser: {User.Identity.Name} Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(NewspaperController)} Method: {nameof(NewspaperController.Create)}");

                return View();
            }
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult CreateIssue(int id)
        {
            var newspaper = _newspaperLogic.GetAllSpecified().Where(x => x.Id == id).FirstOrDefault();

            _logger.LogInformation($"Message: Admin with login '{User.Identity.Name}' opened CreateNewspaperIssue view with id = {id}. Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(NewspaperController)} Method: {nameof(NewspaperController.CreateIssue)}");

            return View(newspaper);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult CreateIssue(Newspaper inputNewspaperIssue)
        {
            try
            {
                Newspaper issueToDB = new Newspaper(
                    inputNewspaperIssue.Title,
                    inputNewspaperIssue.PlaceOfPublication,
                    inputNewspaperIssue.PublishingHouse,
                    (int)inputNewspaperIssue.PublicationOrApplicationYear,
                    inputNewspaperIssue.NumberOfPages,
                    inputNewspaperIssue.ReleaseDate,
                    inputNewspaperIssue.Note,
                    inputNewspaperIssue.IssueNumber,
                    inputNewspaperIssue.ISSN
                    );

                var issueId = _newspaperLogic.Add(issueToDB);

                _logger.LogInformation($"Message: Admin with login '{User.Identity.Name}' added new newspaper issue with id = {issueId}. Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(NewspaperController)} Method: {nameof(NewspaperController.CreateIssue)}");

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                _logger.LogError($"ErrorMessage: {e.Message} CurrentUser: {User.Identity.Name} Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(NewspaperController)} Method: {nameof(NewspaperController.CreateIssue)}");

                return View();
            }
        }

        // GET: NewspaperController/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: NewspaperController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(Newspaper newspaper)
        {
            try
            {
                _newspaperLogic.Edit(newspaper);

                _logger.LogInformation($"Message: Admin with login '{User.Identity.Name}' edited newspaper with id = {newspaper.Id}. Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(NewspaperController)} Method: {nameof(NewspaperController.Edit)}");

                return RedirectToAction(nameof(Index), "Catalog");
            }
            catch (Exception e)
            {
                _logger.LogError($"ErrorMessage: {e.Message} CurrentUser: {User.Identity.Name} Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(NewspaperController)} Method: {nameof(NewspaperController.Edit)}");

                return View();
            }
        }

        // GET: NewspaperController/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: NewspaperController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ROKO.Lib.PL.WebUI/Controllers/PatentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

using ROKO.Lib.BLL.Interface;
using ROKO.Lib.Entities;

using System;
using System.Collections.Generic;
using System.Linq;

namespace ROKO.Lib.PL.WebUI.Controllers
{
    public class PatentController : Controller
    {
        private readonly ICatalogUnitLogic<Patent> _patentLogic;
        private readonly IAuthorLogic _authorLogic;

        private readonly ILogger<PatentController> _logger;

        public PatentController(ICatalogUnitLogic<Patent> patentLogic, IAuthorLogic authorLogic, ILogger<PatentController> logger)
        {
            _patentLogic = patentLogic;
            _authorLogic = authorLogic;

            _logger = logger;
        }

        // GET: PatentController
        public ActionResult Index()
        {
            IEnumerable<Patent> patents = _patentLogic.GetAllSpecified();
            return View(patents);
        }

        // GET: PatentController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PatentController/Create
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            ViewBag.authors = _authorLogic.GetAuthors().Select(x => new SelectListItem { Value = x.AuthorID.ToString(), Text = x.FirstName + " " + x.LastName }).ToList();

            _logger.LogInformation($"Message: Admin with login '{User.Identity.Name}' opened Patent Creating view. Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(PatentController)} Method: {nameof(PatentController.Create)}");

            return View("CreatePatentWithAuthors");
        }

        // POST: PatentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create(Patent patent, IEnumerable<int> authors)
        {
            try
            {
                var patentId = _patentLogic.Add(patent);

                _authorLogic.AddAuthorsToLibraryObject(patentId, authors);

                _logger.LogInformation($"Message: Admin with login '{User.Identity.Name}' added new patent with id = {patentId}. Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(PatentController)} Method: {nameof(PatentController.Create)}");

                return RedirectToAction("Index", "Catalog");
            }
            catch (Exception e)
            {
                _logger.LogError($"ErrorMessage: {e.Message} CurrentUser: {User.Identity.Name} Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(PatentController)} Method: {nameof(PatentController.Create)}");

                return View();
            }
        }

        // GET: PatentController/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PatentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(Patent patent)
        {
            try
            {
                _patentLogic.Edit(patent);

                _logger.LogInformation($"Message: Admin with login '{User.Identity.Name}' edited patent with id = {patent.Id}. Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(PatentController)} Method: {nameof(PatentController.Edit)}");

                return RedirectToAction(nameof(Index), "Catalog");
            }
            catch (Exception e)
            {
                _logger.LogError($"ErrorMessage: {e.Message} CurrentUser: {User.Identity.Name} Time: {DateTime.UtcNow} Layer: {nameof(PL)} Class: {nameof(PatentController)} Method: {nameof(PatentController.Edit)}");

                return View("EditErrorGet");
            }
        }

        // GET: PatentController/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PatentController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ROKO.Lib.PL.WebUI/Views/Catalog/BookDetails.cshtml
@model ROKO.Lib.Entities.Book

@{
    ViewData["Title"] = "BookDetails";
}

<h1>Book Details</h1>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Authors)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Authors)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PlaceOfPublication)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PlaceOfPublication)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublishingHouse)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublishingHouse)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublicationOrApplicationYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublicationOrApplicationYear)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfPages)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumberOfPages)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
    </dl>
</div>
<div>
    @if (User.IsInRole("Administrator"))
    {
        Html.ActionLink("Edit", "Edit", new { id = Model.Id });
    }
    <a asp-action="Index">Back to List</a>
</div>

ROKO.Lib.PL.WebUI/Views/Catalog/DeleteBook.cshtml
@model ROKO.Lib.Entities.Book

@{
    ViewData["Title"] = "DeleteBook";
}

<h1>Delete Book</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PlaceOfPublication)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PlaceOfPublication)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublishingHouse)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublishingHouse)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublicationOrApplicationYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublicationOrApplicationYear)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfPages)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumberOfPages)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
    </dl>

    <form asp-action="Delete">
        @Html.AntiForgeryToken()
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ROKO.Lib.PL.WebUI/Views/Catalog/EditBookGet.cshtml
@model ROKO.Lib.Entities.Book

@{
    ViewData["Title"] = "EditBookGet";
}

<h1>Book Editing</h1>

<h4>Information of Book you have chosen for editing:</h4>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Authors)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlaceOfPublication)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishingHouse)
            </th>
            <th>
                <text>PublicationYear</text>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfPages)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ISBN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Note)
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => Model.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Title)
            </td>
            <td>
                @foreach (var author in Model.Authors)
                {
                    <pre>@author.ToString()</pre>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.PlaceOfPublication)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.PublishingHouse)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.PublicationOrApplicationYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.NumberOfPages)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.ISBN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Note)
            </td>
        </tr>
    </tbody>
</table>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Book">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>@Html.HiddenFor(model => model.Id)</div>
            <div>@Html.HiddenFor(model => model.Type)</div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaceOfPublication" class="control-label"></label>
                <input asp-for="PlaceOfPublication" class="form-control" />
                <span asp-validation-for="PlaceOfPublication" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishingHouse" class="control-label"></label>
                <input asp-for="PublishingHouse" class="form-control" />
                <span asp-validation-for="PublishingHouse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublicationOrApplicationYear" class="control-label"></label>
                <input asp-for="PublicationOrApplicationYear" class="form-control" />
                <span asp-validation-for="PublicationOrApplicationYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfPages" class="control-label"></label>
                <input asp-for="NumberOfPages" class="form-control" />
                <span asp-validation-for="NumberOfPages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.AntiForgeryToken()
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Catalog List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ROKO.Lib.PL.WebUI/Views/Catalog/NewCatalogRequirementsIndex.cshtml
@model IEnumerable<ROKO.Lib.PL.WebUI.Models.NewCatalogRequirementsViewModel>

@{
    ViewData["Title"] = "NewCatalogRequirementsIndex";
}

<h1>All Catalog</h1>

@if (User.IsInRole("Administrator"))
{
    <p>
        <a asp-action="Create" asp-controller="Book">Create New Book</a>
    </p>
    <p>
        <a asp-action="Create" asp-controller="Newspaper">Create New Newspaper</a>
    </p>
    <p>
        <a asp-action="Create" asp-controller="Patent">Create New Patent</a>
    </p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Identificator)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfPages)
            </th>
            @if (User.IsInRole("Administrator"))
            {
                <th></th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink($"{item.Name}", "Details", new { id = item.UnitId })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Identificator)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfPages)
                </td>
                @if (User.IsInRole("Administrator"))
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.UnitId }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.UnitId })
                    </td>
                }
            </tr>
        }
    </tbody>
</table>
<br />

ROKO.Lib.PL.WebUI/Views/Catalog/PagedIndex.cshtml
@model ROKO.Lib.PL.WebUI.Models.CatalogIndexViewModel
@using ROKO.Lib.PL.WebUI.Models
@{
    ViewData["Title"] = "PagedIndex";
}

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

<h1>All Catalog</h1>

@if (User.IsInRole("Administrator"))
{
    <span>Create New: </span>
    <a asp-action="Create" asp-controller="Book">Book</a>
    <a asp-action="Create" asp-controller="Newspaper">Newspaper</a>
    <a asp-action="Index" asp-controller="Newspaper">Newspaper Issue</a>
    <a asp-action="Create" asp-controller="Patent">Patent</a>
}

<table class="table">
    <thead>
        <tr>
            <th>
                Наименование
            </th>
            <th>
                Идентификатор
            </th>
            <th>
                Количество страниц
            </th>
            @if (User.IsInRole("Administrator"))
            {
                <th></th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.CatalogElements)
        {
            <tr>
                <td>
                    @Html.ActionLink($"{item.Name}", "Details", new { id = item.UnitId })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Identificator)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfPages)
                </td>
                @if (User.IsInRole("Administrator"))
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.UnitId }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.UnitId })
                    </td>
                }
            </tr>
        }
    </tbody>
</table>
<div class="container" style="margin-bottom:75px;">

    @if (Model.PageInfo.EndPage > 1)
    {
        <ul class="pagination justify-content-center">
            @if (Model.PageInfo.CurrentPage > 0)
            {
                <li class="page-item">
                    <a class="page-link" href="~/Catalog/Index">First</a>
                </li>
            }

            @for (var page = Model.PageInfo.StartPage; page <= Model.PageInfo.EndPage; page++)
            {
                <li class="@(page == Model.PageInfo.CurrentPage ? "page-item active" : "page-item")" aria-current="page">
                    @if (page == Model.PageInfo.CurrentPage)
                    {
                        <span class="page-link" href="~/Catalog/Index?page=@(page)"> @(page) </span>
                    }
                    else
                    {
                        <a class="page-link" href="~/Catalog/Index?page=@(page)"> @(page) </a>
                    }
                </li>
            }

            @if (Model.PageInfo.CurrentPage <= Model.PageInfo.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" href="~/Catalog/Index?page=@(Model.PageInfo.TotalPages)">Last</a>
                </li>
            }
        </ul>
    }
</div>